name: 'Setup Node.js Project'
description: 'Setup Node.js environment and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    
    - name: Install dependencies
      shell: bash
      run: npm ci

